baseURL = "https://diegobecker.com.br/"
title = "Diego Becker"
theme = "PaperMod"

defaultContentLanguage = "pt"
languageCode = "pt-br"

[pagination]
  pagerSize = 5

[params]
  defaultTheme = "auto"
  showReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  disableScrollToTop = false
  ShowLanguageSwitcher = false
  mainSections = []
  

[[menu.main]]
  name = "Artigos"
  url = "posts/"
  weight = 1

[[menu.main]]
  name = "Sobre"
  url = "about/"
  weight = 2