baseURL = "https://diegobecker.com.br/"
title = "Diego Becker"
theme = "PaperMod"
languageCode = "en-us"

[pagination]
  pagerSize = 5

[params]
  defaultTheme = "auto"
  showReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  disableScrollToTop = false
  

[[menu.main]]
  name = "Profile"
  url = "profile/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "about/"
  weight = 2
