name: Hugo Build & Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Hugo site to S3
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --minify

      - name: Deploy to S3
        run: aws s3 sync ./public s3://www.diegobecker.com.br --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: sa-east-1
